[workspace]
members = [
    "evm-adapters",
    "utils",
    "cast",
    "forge",
    "cli",
    "cli/test-utils",
    "config",
]

# Binary size optimizations
[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
debug = true

# Patch ethers-rs with a local checkout
[patch."https://github.com/gakonst/ethers-rs"]
ethers = { git = "https://github.com/brockelmore/ethers-rs" }
ethers-core = { git = "https://github.com/brockelmore/ethers-rs" }
ethers-providers = { git = "https://github.com/brockelmore/ethers-rs" }
ethers-signers = { git = "https://github.com/brockelmore/ethers-rs" }
ethers-etherscan = { git = "https://github.com/brockelmore/ethers-rs" }
ethers-solc = { git = "https://github.com/brockelmore/ethers-rs" }